AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  Crawlers!
Parameters:
  SlackDomain:
    Type: string
    Default: lifzar
  SecretForSlackKey:
    Type: String
    Default: SecretForSlackKey-mODtNGLkK3nO
  AlamodomeChannel:
    Type: String
    Default: C01T9409D42
  AlbertsonsChannel:
    Type: String
    Default: C01T940N57U
  BellCountyChannel:
    Type: String
    Default: C01TYTKJ5MW
  CoryellHealthChannel:
    Type: String
    Default: C01SUAN2T71
  FallsHospitalChannel:
    Type: String
    Default: C01T61PP53P
  HebChannel:
    Type: String
    Default: C01T144UM54
  UniversityChannel:
    Type: String
    Default: C01TMN4KTFB
  WalgreensChannel:
    Type: String
    Default: C01TXM7NHHN
  WalmartChannel:
    Type: String
    Default: C01T17D2F5L

Resources:
  CrawlAlamodome:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Runtime: nodejs12.x
      Handler: crawl.alamodome
      MemorySize: 128
      Timeout: 300
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn:
              Ref: SecretForSlackKey
      Environment:
        Variables:
          SLACK_DOMAIN:
            Ref: SlackDomain
          SLACK_SECRET:
            Ref: SlackSecret
          ALAMODOME_CHANNEL:
            Ref: AlamodomeChannel
      Events:
        CrawlAlamodome:
          Type: Schedule
          Properties:
            Enabled: true
            Schedule: rate(1 minute)
  CrawlAlbertsons:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Runtime: nodejs12.x
      Handler: crawl.albertsons
      MemorySize: 128
      Timeout: 300
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn:
              Ref: SecretForSlackKey
      Environment:
        Variables:
          SLACK_DOMAIN:
            Ref: SlackDomain
          SLACK_SECRET:
            Ref: SlackSecret
          ALBERTSONS_CHANNEL:
            Ref: AlbertsonsChannel
      Events:
        CrawlAlbertsons:
          Type: Schedule
          Properties:
            Enabled: true
            Schedule: rate(1 minute)
  CrawlBellCounty:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Runtime: nodejs12.x
      Handler: crawl.bellCounty
      MemorySize: 128
      Timeout: 300
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn:
              Ref: SecretForSlackKey
      Environment:
        Variables:
          SLACK_DOMAIN:
            Ref: SlackDomain
          SLACK_SECRET:
            Ref: SlackSecret
          BELL_COUNTY_CHANNEL:
            Ref: BellCountyChannel
      Events:
        CrawlBellCounty:
          Type: Schedule
          Properties:
            Enabled: true
            Schedule: rate(1 minute)
  CrawlCoryellHealth:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Runtime: nodejs12.x
      Handler: crawl.coryellHealth
      MemorySize: 128
      Timeout: 300
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn:
              Ref: SecretForSlackKey
      Environment:
        Variables:
          SLACK_DOMAIN:
            Ref: SlackDomain
          SLACK_SECRET:
            Ref: SlackSecret
          CORYELL_HEALTH_CHANNEL:
            Ref: CoryellHealthChannel
      Events:
        CrawlCoryellHealth:
          Type: Schedule
          Properties:
            Enabled: true
            Schedule: rate(1 minute)
  CrawlFallsHospital:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Runtime: nodejs12.x
      Handler: crawl.fallsHospital
      MemorySize: 128
      Timeout: 300
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn:
              Ref: SecretForSlackKey
      Environment:
        Variables:
          SLACK_DOMAIN:
            Ref: SlackDomain
          SLACK_SECRET:
            Ref: SlackSecret
          FALLS_HOSPITAL_CHANNEL:
            Ref: FallsHospitalChannel
      Events:
        CrawlFallsHospital:
          Type: Schedule
          Properties:
            Enabled: true
            Schedule: rate(1 minute)
  CrawlHeb:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Runtime: nodejs12.x
      Handler: crawl.heb
      MemorySize: 128
      Timeout: 300
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn:
              Ref: SecretForSlackKey
      Environment:
        Variables:
          SLACK_DOMAIN:
            Ref: SlackDomain
          SLACK_SECRET:
            Ref: SlackSecret
          HEB_CHANNEL:
            Ref: HebChannel
      Events:
        CrawlHeb:
          Type: Schedule
          Properties:
            Enabled: true
            Schedule: rate(1 minute)
  CrawlUniversity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Runtime: nodejs12.x
      Handler: crawl.university
      MemorySize: 128
      Timeout: 300
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn:
              Ref: SecretForSlackKey
      Environment:
        Variables:
          SLACK_DOMAIN:
            Ref: SlackDomain
          SLACK_SECRET:
            Ref: SlackSecret
          UNIVERISITY_CHANNEL:
            Ref: UniversityChannel
      Events:
        CrawlUniversity:
          Type: Schedule
          Properties:
            Enabled: true
            Schedule: rate(1 minute)
  CrawlWalgreens:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Runtime: nodejs12.x
      Handler: crawl.walgreens
      MemorySize: 128
      Timeout: 300
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn:
              Ref: SecretForSlackKey
      Environment:
        Variables:
          SLACK_DOMAIN:
            Ref: SlackDomain
          SLACK_SECRET:
            Ref: SlackSecret
          WALGREENS_CHANNEL:
            Ref: WalgreensChannel
      Events:
        CrawlWalgreens:
          Type: Schedule
          Properties:
            Enabled: true
            Schedule: rate(1 minute)
  CrawlWalmart:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Runtime: nodejs12.x
      Handler: crawl.walmart
      MemorySize: 128
      Timeout: 300
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn:
              Ref: SecretForSlackKey
      Environment:
        Variables:
          SLACK_DOMAIN:
            Ref: SlackDomain
          SLACK_SECRET:
            Ref: SlackSecret
          WALMART_CHANNEL:
            Ref: WalmartChannel
      Events:
        CrawlWalmart:
          Type: Schedule
          Properties:
            Enabled: true
            Schedule: rate(1 minute)
